language: objective-c
osx_image: xcode7.1
script: 
    - xcodebuild -scheme Create\ Release\ Folder
    - xcodebuild test -scheme APSHTTPClientTests -destination 'platform=iOS Simulator,name=iPhone 6'